##
## My Working Eslint Configuration File
##  see the README.md for notes and descriptions
##
##  INIT: npm install -D eslint eslint-config-prettier eslint-plugin-react
##  eslint-plugin-header
##  babel-eslint
##  eslint-plugin-flowtype
##  eslint plugin-react
##

env:
  browser: true
  es6: true
  node: true
  mocha: true
  # atomtest: true
  # jasmine: true

# settings:
#   import/resolver:
#     webpack:
#       config: ./webpack.config.js

extends:
  - eslint:recommended
#  - prettier
#  - prettier/flowtype

parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module

# NOTE: globals can also be sepecified on a per file basis with /* global <var_name> */
globals:
  # chai
  expect: readonly
  # sinon global if setting up test bootstrap
  sandbox: readonly # TODO: Identify where

# plugins:
#  - react
#  - header
#  - prettier
#  - flowtype
#  - plugin:flowtype/recommended


# Rules for only some file locations/paths (globs)
# overrides:
#   - files:
#     - src/*.js
#     excludedFiles: src/*.spec.js
#     rules:
#       header/header:
#         - warn
#         - block
#         - pattern: description

# Custom Rules Below (can be disabled with /* eslint disable [<rule_name>,<comma_separated>])
rules:
    # Flow Type Rules
  # flowtype/require-return-type:
  #   - warn
  #   - always
  #   - excludeMatching:
  #     - "spec.js"
  # flowtype/require-parameter-type:
  #   - warn
  # flowtype/no-weak-types:
  #   - warn

  # Documentation Rules
  # header/header:
  #   - warn
  #   - block
  #   - pattern: description
  # valid-jsdoc: error
  # require-jsdoc:
  #   - warn
  #   - require:
  #       FunctionDeclaration: true
  #       MethodDefinition: true
  #       ClassDeclaration: true

  # File Conventions
  max-len:
    - warn
    - code: 110
      ignoreUrls: true
  max-lines:
    - warn
    - max: 500
      skipComments: true
  eol-last:
    - error
    - always
  linebreak-style:
    - error
    - unix

  # Basic Rules
  no-var: error
  prefer-const: error
  no-shadow: error

  no-duplicate-imports: error
  class-methods-use-this: warn
  require-await: warn

  no-console:
    - warn
  no-alert:
    - error

  no-empty-function:
    - warn

  eqeqeq:
    - error
    - always

  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-lonely-if: error

  # Spacing
  no-trailing-spaces: error
  space-infix-ops: error
  space-before-blocks: error
  spaced-comment:
    - error
    - always
  space-in-parens:
    - error
    - never
  space-before-function-paren:
    - error
    - always
  keyword-spacing:
    - error
    - before: true
      after: true

  # Array/Comma Spacing
  comma-spacing:
    - error
    - after: true
  array-bracket-newline:
    - error
    - multiline: true
      minItems: 3
  array-element-newline:
    - error
    - multiline: true
      minItems: 3
  comma-dangle:
    - error
    - arrays: only-multiline
      objects: only-multiline
      imports: never
      exports: never
      functions: ignore

  # Object Spacing
  key-spacing:
    - error
    - afterColon: true
  object-curly-spacing:
    - error
    - always
  object-curly-newline:
    - error
    - consistent: true

  # Arrow Function Conventions
  arrow-body-style:
    - error
    - always
  arrow-parens:
    - error
    - always
  arrow-spacing: error
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
